{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-moshpit
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - altair
    - beautifulsoup4
    - bracken
    - busco ==5.5.0
    - diamond
    - eggnog-mapper >=2.1.10
    - gfatools
    - kaiju
    - kraken2
    - metabat2
    - pandas
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - q2-assembly {{ qiime2_epoch }}.*
    - q2-quality-control {{ qiime2_epoch }}.*
    - samtools
    - seqtk
    - tqdm
    - xmltodict
    - pyhmmer

test:
  requires:
    - coverage
    - pytest-cov
    - parameterized
  imports:
    - q2_moshpit
    - qiime2.plugins.moshpit
  commands:
    - pytest --cov q2_moshpit --cov-report xml:coverage.xml --pyargs q2_moshpit

about:
  home: https://github.com/bokulich-lab/q2-moshpit
  license: BSD-3-Clause
  license_family: BSD
